#!/usr/bin/env bash

if [[ $# != 1 ]] ; then
	echo "Please specify one of major, minor, or patch"
	exit 1
fi
case $1 in
	major|minor|patch)
		;;
	*)
		echo "Invalid option. Specify one of major, minor, or patch"
		exit 1
		;;
esac
version=$(/Users/suderman/bin/bump $1 $(cat VERSION))
echo $version > VERSION
echo "New version is $(cat VERSION)"
