name: Repository configuration
on:
  workflow_dispatch:
    inputs:
      values_file:
        description: 'Values file to use for the Galaxy Helm chart'
        required: false
jobs:
  install-galaxy:
    name: Install Galaxy and run a benchmark with ABM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: ksuderman/github-action-galaxy-k8s@master
        with:
          api-key: secret
          values_file: values.yml

      - name: Get Helm values
        shell: bash
        run: |
          helm get values galaxy -n galaxy --all --output yaml

      - name: Install ABM
        shell: bash
        run: |
          pip install gxabm
          abm --version

      - name: Create a Galaxy user
        shell: bash
        run: |
          cat > /tmp/user.json << EOF
          {
              "email": "admin@example.com",
                "password": "galaxypassword",
                "username": "admin"
          }
          EOF
          curl -X POST -H "x-api-key: secret" -H "Content-Type: application/json" -d @/tmp/user.json http://localhost/api/users | jq

      - name: Run ABM using configuration defined in the repository
        shell: bash
        run: |
          # Create a Galaxy user and an API key
          abm config key localhost changeme
          abm config show localhost
          # Import a workflow and a history
          abm localhost workflow import variant
          abm localhost history import variant-2g
          # Validate and run the benchmark
          abm localhost benchmark validate benchmark.yml          
          abm localhost benchmark run benchmark.yml 
          abm localhost history list
          abm localhost jobs list
          
