name: Test the galaxy-k8s action
on:
  workflow_dispatch:
    inputs:
      values_file:
        description: 'Values file to use for the Galaxy Helm chart'
        required: false
      from-repo:
        description: 'Use configuration files from the repository'
        type: boolean
        required: false
        default: false
jobs:
  install-galaxy:
    name: Install Galaxy and run a benchmark with ABM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: ksuderman/github-action-galaxy-k8s@master
        with:
          api-key: secret
          values_file: values.yml

      - name: Install and configure ABM, then run a benchmark
        shell: bash
        run: |
          # Install ABM
          pip install gxabm
          abm --version

      - name: Run ABM using configuration defined in the workflow
        shell: bash
        if: ${{ github.event.inputs.from-repo == false }}
        run: |        
          # Configure ABM
          mkdir -p $HOME/.abm
          abm config create localhost $HOME/.kube/config
          abm config key localhost secret
          abm config url localhost http://localhost
          abm config list
          ls $HOME/.abm
          cat $HOME/.abm/profile.yml
          # Create a Galaxy user and an API key
          key=$(abm localhost user create admin admin@example.com galaxypassword | jq -r .key)
          abm config key localhost $key
          # Import a workflow, a history, and generate a benchmark
          abm localhost workflow import https://benchmarking-inputs.s3.amazonaws.com/Variant/Galaxy-Workflow-Variant_analysis_on_WGS_PE_data.ga
          abm localhost history import https://benchmarking-inputs.s3.amazonaws.com/Variant/Variant-calling-inputs---2GB.rocrate.zip
          cat > benchmark.yml << EOF
            - output_history_base_name: Variant-Calling
              workflow_id: Variant analysis on WGS PE data
              runs:
              - history_name: 2GB
                inputs:
                - name: Paired Collection
                  collection: SRR24043307-2GB
                - name: GenBank genome
                  dataset_id: GRCh38.p14.gbff.gz
                - name: Name for genome database
                  value: h38          
          EOF
          # Validate and run the benchmark
          abm localhost benchmark validate benchmark.yml          
          abm localhost benchmark run benchmark.yml 
          abm localhost history list
          abm localhost jobs list

      - name: Run ABM using configuration defined in the workflow
        shell: bash
        if: ${{ github.event.inputs.from-repo }}
        run: |
          # Create a Galaxy user and an API key
          key=$(abm localhost user create admin admin@example.com galaxypassword | jq -r .key)
          abm config key localhost $key
          # Import a workflow, a history, and generate a benchmark
          abm localhost workflow import https://benchmarking-inputs.s3.amazonaws.com/Variant/Galaxy-Workflow-Variant_analysis_on_WGS_PE_data.ga
          abm localhost history import https://benchmarking-inputs.s3.amazonaws.com/Variant/Variant-calling-inputs---2GB.rocrate.zip
          cat > benchmark.yml << EOF
            - output_history_base_name: Variant-Calling
              workflow_id: Variant analysis on WGS PE data
              runs:
              - history_name: 2GB
                inputs:
                - name: Paired Collection
                  collection: SRR24043307-2GB
                - name: GenBank genome
                  dataset_id: GRCh38.p14.gbff.gz
                - name: Name for genome database
                  value: h38          
          EOF
          # Validate and run the benchmark
          abm localhost benchmark validate benchmark.yml          
          abm localhost benchmark run benchmark.yml 
          abm localhost history list
          abm localhost jobs list
          
          #          mkdir -p ~/.abm
#          cat << EOF >> ~/.abm/profile.yml
#          localhost:
#            url: http://localhost
#            key: secret
#            kube: $HOME/.kube/config
#          EOF

#      - name: Create a Galaxy user
#        run: |
#          echo "Creating a Galaxy user"
#          cat > /tmp/user.json << EOF
#          {
#            "username": "admin",
#            "email": "admin@example.org",
#            "password": "password"
#          }
#          EOF
#          curl -X POST -H "x-api-key: secret" -H "Content-Type: application/json" -d @/tmp/user.json http://localhost/api/users | jq
          

