name: Package and publish the chart
on:
  workflow_dispatch:
    inputs:
      manual-package-invocation:
        description: 'Package (y/n)?'
        required: true
        default: 'y'
      branch-name:
        description: 'Branch name to package'
        required: true
jobs:
  tag-and-release:
    name: Create a tag and GitHub release for this version.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tag and release
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          version=v$(cat VERSION)
          git tag -a $version -m "Automatic release of $version"
          git push origin $version
          gh release create $version --generate-notes --latest
