name: Test the galaxy-k8s action
on:
  workflow_dispatch:
    inputs:
      values_file:
        description: 'Values file to use for the Galaxy Helm chart'
        required: false

jobs:
  install-galaxy:
    name: Install Galaxy and create a user
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
           persist-credentials: false

      - uses: ksuderman/github-action-galaxy-k8s@master
        with:
          api-key: secret
          values_file: values.yml

      - name: Create a Galaxy user
        run: |
          echo "Creating a Galaxy user"
          cat > /tmp/user.json << EOF
          {
            "username": "admin",
            "email": "admin@example.org",
            "password": "password"
          }
          EOF
          curl -X POST -H "x-api-key: secret" -H "Content-Type: application/json" -d @/tmp/user.json http://localhost:8080/api/users
          

