name: Test Pull Request
on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for test script
        id: check_test
        run: |
          if [ -f "test.sh" ]; then
            echo "test_exists=true" >> $GITHUB_OUTPUT
          else
            echo "test_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Run test script
        if: steps.check_test.outputs.test_exists == 'true'
        run: |
          chmod +x test.sh
          ./test.sh

      - name: No tests found
        if: steps.check_test.outputs.test_exists == 'false'
        run: echo "No test.sh file found. Skipping tests."
